
// TripPlan interface defines the structure of the itinerary generated by AI.
export interface TripPlan {
  destination: string;
  summary: string;
  highlights: string[];
  itinerary: {
    day: number;
    activity: string;
    description: string;
  }[];
  budget_level: string;
}

export interface Destination {
  id: string;
  name: string;
  location: string;
  image: string;
  price: string;
  rating: number;
  tags: string[];
  summary: string;
  included: string[];
}

export enum Vibe {
  Adventure = 'Adventure',
  Relaxation = 'Relaxation',
  Culture = 'Culture',
  Luxury = 'Luxury'
}
